os module needs to be imported
gautomatch viewer fails with message

  File "/home/roberto/scipion3/Plugins/scipion-em-gautomatch/gautomatch/viewers.py", line 123, in _viewParam
    micsFn = os.path.join(tmpDir, micSet.getName() + '_micrographs.xmd')
NameError: name 'os' is not defined

therefore os needs to be imported. I guess in previous versions of scipio os was imported in another of the imported modules.